"""initial_migration

Revision ID: c37145345dad
Revises: 
Create Date: 2026-06-09 18:37:53.890176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37145345dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteorological',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freak', sa.String(length=120), nullable=False),
    sa.Column('cat', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freak_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=700), nullable=False),
    sa.ForeignKeyConstraint(['freak_id'], ['meteorological.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('meteorological')
    # ### end Alembic commands ###
